version: "2"

services:
    bot: 
        image: sad0vnikov/wundergram
        restart: unless-stopped
        env_file: ".env"
        ports:
            - "8080:8080"
        volumes:
            - "./wundergram.db:/wundergram.db"